name = "dietitianfinder"
compatibility_date = "2023-12-01"

[build]
command = "npx next build"
pages_build_output_dir = ".next/standalone"

[site]
bucket = ".next/standalone"

[build.environment]
NODE_VERSION = "20.11.1"

[[build.upload]]
type = "Pages"
dir = ".next/standalone"
main = ".next/server.js" 